# syntax=docker/dockerfile:1
# docker.io/docker/dockerfile:1

FROM alpine:edge AS build

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

WORKDIR /app

RUN apk add --no-cache skopeo tini

RUN apk add --no-cache helm kubectl --repository=http://mirrors.aliyun.com/alpine/edge/testing/

ENV VERSION ${VERSION}
